%% SCRIPT PARA SIMULAR Y GRAFICAR CONTROLADORES
function graficas_controladores(t,q,qd,q_ref,qd_ref,Im)

figure(1);subplot(231);plot(t,q_ref(:,1),t,q(:,1));grid;xlabel('Tiempo [s]');ylabel('Posicion angular q1 [rad]');...
    subplot(232);plot(t,q_ref(:,2),t,q(:,2);grid;xlabel('Tiempo [s]');ylabel('Posicion angular q2[rad]');...
    subplot(233);plot(t,q_ref(:,3),t,q(:,3);grid;xlabel('Tiempo [s]');ylabel('Posicion angular q3[rad]');...
    
    subplot(234);plot(t,q_ref(:,1)-q(:,1));grid;xlabel('Tiempo [s]');ylabel('Error relativo q1');...
    subplot(235);plot(t,q_ref(:,2)-q(:,2);grid;xlabel('Tiempo [s]');ylabel('Error relativo q2');...
    subplot(236);plot(t,q_ref(:,3)-q(:,3);grid;xlabel('Tiempo [s]');ylabel('Error relativo q3');...
    
figure(2);subplot(231);plot(t,qd_ref(:,1),t,qd(:,1));grid;xlabel('Tiempo [s]');ylabel('Velocidad angular qd1 [rad/s]');...
    subplot(232);plot(t,qd_ref(:,2),t,qd(:,2);grid;xlabel('Tiempo [s]');ylabel('Velocidad angular qd2 [rad/s]');...
    subplot(233);plot(t,qd_ref(:,3),t,qd(:,3);grid;xlabel('Tiempo [s]');ylabel('Velocidad angular qd3 [rad/s]');...
    
    subplot(234);plot(t,qd_ref(:,1)-qd(:,1));grid;xlabel('Tiempo [s]');ylabel('Error relativo qd1');...
    subplot(235);plot(t,qd_ref(:,2)-qd(:,2);grid;xlabel('Tiempo [s]');ylabel('Error relativo qd2');...
    subplot(236);plot(t,qd_ref(:,3)-qd(:,3);grid;xlabel('Tiempo [s]');ylabel('Error relativo qd3');...
    
figure(3);title('Excitacion motor 1');subplot(311);plot(t,Im(:,1));grid;xlabel('Tiempo [s]');ylabel('Intensidad [A]');...
    title('Excitacion motor 2');subplot(312);plot(t,Im(:,2));grid;xlabel('Tiempo [s]');ylabel('Intensidad [A]');...
    title('Excitacion motor 3');subplot(313);plot(t,Im(:,3));grid;xlabel('Tiempo [s]');ylabel('Intensidad [A]');

end