%% SCRIPT PARA SIMULAR Y GRAFICAR CONTROLADORES
function graficas_controladores(t,q,qd,q_ref,qd_ref,ref,xyz,Im)

figure();subplot(231);plot(t,q_ref(:,1),t,q(:,1));grid;xlabel('Tiempo [s]');title('Posicion angular q1');ylabel('qr_1 vs q_1 [rad]');...
    subplot(232);plot(t,q_ref(:,2),t,q(:,2));grid;xlabel('Tiempo [s]');title('Posicion angular q2');ylabel('qr_2 vs q_2 [rad]');...
    subplot(233);plot(t,q_ref(:,3),t,q(:,3));grid;xlabel('Tiempo [s]');title('Posicion angular q3');ylabel('qr_3 vs q_3 [rad]');...
    
    subplot(234);plot(t,q_ref(:,1)-q(:,1));grid;xlabel('Tiempo [s]');title('Error relativo q1');ylabel('qr_1 -q_1 [rad]');...
    subplot(235);plot(t,q_ref(:,2)-q(:,2));grid;xlabel('Tiempo [s]');title('Error relativo q2');ylabel('qr_2 -q_2 [rad]');...
    subplot(236);plot(t,q_ref(:,3)-q(:,3));grid;xlabel('Tiempo [s]');title('Error relativo q3');ylabel('qr_3 -q_3 [rad]'); ...
    
figure();subplot(231);plot(t,qd_ref(:,1),t,qd(:,1));grid;xlabel('Tiempo [s]');title('Velocidad angular qd1 ');ylabel('qdr_1 vs qd_1 [rad/s]');...
    subplot(232);plot(t,qd_ref(:,2),t,qd(:,2));grid;xlabel('Tiempo [s]');title('Velocidad angular qd2 ');ylabel('qdr_2 vs qd_2 [rad/s]');...
    subplot(233);plot(t,qd_ref(:,3),t,qd(:,3));grid;xlabel('Tiempo [s]');title('Velocidad angular qd3 ');ylabel('qdr_3 vs qd_3 [rad/s]');...
    
    subplot(234);plot(t,qd_ref(:,1)-qd(:,1));grid;xlabel('Tiempo [s]');title('Error relativo qd1');ylabel('qdr_1 - qd_1 [rad/s]');...
    subplot(235);plot(t,qd_ref(:,2)-qd(:,2));grid;xlabel('Tiempo [s]');title('Error relativo qd2');ylabel('qdr_2 - qd_2 [rad/s]');...
    subplot(236);plot(t,qd_ref(:,3)-qd(:,3));grid;xlabel('Tiempo [s]');title('Error relativo qd3');ylabel('qdr_3 - qd_3 [rad/s]');...
    
figure();subplot(311);title('Excitacion motor 1');plot(t,Im(:,1));grid;xlabel('Tiempo [s]');ylabel('Intensidad [A]');...
    subplot(312);title('Excitacion motor 2');plot(t,Im(:,2));grid;xlabel('Tiempo [s]');ylabel('Intensidad [A]');...
    subplot(313);title('Excitacion motor 3');plot(t,Im(:,3));grid;xlabel('Tiempo [s]');ylabel('Intensidad [A]');

figure();plot3(ref(:,1),ref(:,2),ref(:,3),xyz(:,1),xyz(:,2),xyz(:,3));title('Trayectoria en el espacio articular');...
    xlabel('Posicion X');ylabel('Posicion Y');zlabel('Posicion Z');grid;
end