%% SCRIPT PARA PINTAR LAS GRAFICAS

selection='Seleccione que graficas quiere pintar:\n 1.Graficas ideales en tiempo discreto\n 2.Graficas reales en tiempo discreto\n';
selec=input(selection);

if (selec==1)
    figure();subplot(3,1,1);plot(t_D,Im_D(:,1));title('Intensidades en los motores');xlabel('Tiempo [s]');ylabel('Intesidad [A]');grid;...
        subplot(3,1,2);plot(t_D,Im_D(:,2));xlabel('Tiempo [s]');ylabel('Intesidad [A]');grid;...
        subplot(3,1,3);plot(t_D,Im_D(:,3));xlabel('Tiempo [s]');ylabel('Intesidad [A]');grid;

    figure();subplot(3,1,1);plot(t_D,qi_D(:,1));title('Posiciones ideales de las articulaciones');xlabel('Tiempo [s]');ylabel('Posicion [rad]');grid;...
        subplot(3,1,2);plot(t_D,qi_D(:,2));xlabel('Tiempo [s]');ylabel('Posicion [rad]');grid;...
        subplot(3,1,3);plot(t_D,qi_D(:,3));xlabel('Tiempo [s]');ylabel('Posicion [rad]');grid;

    figure();subplot(3,1,1);plot(t_D,qdi_D(:,1));title('Velocidades ideales de las articulaciones');xlabel('Tiempo [s]');ylabel('Velocidad [rad/s]');grid;...
        subplot(3,1,2);plot(t_D,qdi_D(:,2));xlabel('Tiempo [s]');ylabel('Velocidad [rad/s]');grid;...
        subplot(3,1,3);plot(t_D,qdi_D(:,3));xlabel('Tiempo [s]');ylabel('Velocidad [rad/s]');grid;

    figure();subplot(3,1,1);plot(t_D,qddi_D(:,1));title('Aceleraciones ideales de las articulaciones');xlabel('Tiempo [s]');ylabel('Posicion [rad/s^{2}]');grid;...
        subplot(3,1,2);plot(t_D,qddi_D(:,2));xlabel('Tiempo [s]');ylabel('Aceleracion [rad/s^{2}]');grid;...
        subplot(3,1,3);plot(t_D,qddi_D(:,3));xlabel('Tiempo [s]');ylabel('Aceleracion [rad/s^{2}]');grid;
elseif (selec==2)
        figure();subplot(3,1,1);plot(t_D,Im_D(:,1));title('Intensidades en los motores');xlabel('Tiempo [s]');ylabel('Intesidad [A]');grid;...
        subplot(3,1,2);plot(t_D,Im_D(:,2));xlabel('Tiempo [s]');ylabel('Intesidad [A]');grid;...
        subplot(3,1,3);plot(t_D,Im_D(:,3));xlabel('Tiempo [s]');ylabel('Intesidad [A]');grid;

    figure();subplot(3,1,1);plot(t_D,qr_D(:,1));title('Posiciones reales de las articulaciones');xlabel('Tiempo [s]');ylabel('Posicion [rad]');grid;...
        subplot(3,1,2);plot(t_D,qr_D(:,2));xlabel('Tiempo [s]');ylabel('Posicion [rad]');grid;...
        subplot(3,1,3);plot(t_D,qr_D(:,3));xlabel('Tiempo [s]');ylabel('Posicion [rad]');grid;

    figure();subplot(3,1,1);plot(t_D,qdr_D(:,1));title('Velocidades reales de las articulaciones');xlabel('Tiempo [s]');ylabel('Velocidad [rad/s]');grid;...
        subplot(3,1,2);plot(t_D,qdr_D(:,2));xlabel('Tiempo [s]');ylabel('Velocidad [rad/s]');grid;...
        subplot(3,1,3);plot(t_D,qdr_D(:,3));xlabel('Tiempo [s]');ylabel('Velocidad [rad/s]');grid;
end